- urls:
    - https://qiita.com/fujifuji1414/feed.atom
  template: templates/feeds.tmpl
  limit: 4
  sorted: true

- urls:
    - https://zenn.dev/fuuji/feed
  template: templates/feeds.tmpl
  limit: 7
  sorted: true
